package com.flowflex.user;

import com.flowflex.api.ApiModels.*;
import com.flowflex.finance.FinancialRecommendationService;
import com.flowflex.finance.IncomeShockService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.*;

@Service
public class UserService {
    private final UserRepository users; private final ProfileRepository profiles; private final UserLoanRepository loans; private final IncomeTransactionRepository incomes; private final ContributionRepository contributions; private final FinancialRecommendationService engine; private final IncomeShockService shockService;
    public UserService(UserRepository users, ProfileRepository profiles, UserLoanRepository loans, IncomeTransactionRepository incomes, ContributionRepository contributions, FinancialRecommendationService engine, IncomeShockService shockService) { this.users=users; this.profiles=profiles; this.loans=loans; this.incomes=incomes; this.contributions=contributions; this.engine=engine; this.shockService=shockService; }
    @Transactional public UserModels.UserResponse create(UserModels.CreateUser request) { return response(users.save(new User(request.name(), request.occupation(), request.incomeType()))); }
    public User getUser(Long id) { return users.findById(id).orElseThrow(() -> new NoSuchElementException("User not found")); }
    @Transactional public UserModels.UserResponse updateUser(Long id, UserModels.CreateUser request) { User user=getUser(id); user.update(request.name(),request.occupation(),request.incomeType()); return response(user); }
    @Transactional public UserModels.UserResponse saveProfile(Long id, UserModels.ProfileRequest request) {
        User user = getUser(id);
        Double requestedDaily = request.dailyEssentialExpenses();
        Double requestedMonthly = request.monthlyEssentialExpenses();
        double daily = requestedDaily != null && requestedDaily > 0
                ? requestedDaily
                : requestedMonthly != null && requestedMonthly > 0 ? requestedMonthly / 30.0 : 0;
        if (daily <= 0) throw new IllegalArgumentException("Add an essential-expense amount greater than zero.");
        if (request.earningFrequency() == null || request.earningFrequency().isBlank()) throw new IllegalArgumentException("Select an earning frequency.");
        if (request.currentSavings() < 0 || request.protectionDays() < 1) throw new IllegalArgumentException("Savings cannot be negative and protection days must be at least one.");
        FinancialProfile profile = profiles.findByUserId(id).orElse(new FinancialProfile(user, request.earningFrequency(), daily, request.currentSavings(), request.protectionDays()));
        profile.update(request.earningFrequency(), daily, request.currentSavings(), request.protectionDays());
        profiles.save(profile);
        return response(user);
    }
    @Transactional public UserModels.UserResponse saveLoan(Long id, UserModels.LoanRequest request) { User user=getUser(id); Loan loan=loans.findByUserId(id).orElse(new Loan(user,request.hasLoan(),request.outstanding(),request.monthlyTarget(),request.remainingMonths())); loan.update(request.hasLoan(),request.outstanding(),request.monthlyTarget(),request.remainingMonths()); loans.save(loan); return response(user); }
    @Transactional public IncomeTransaction addIncome(Long id, UserModels.IncomeRequest request) { if(request.amount()<0) throw new IllegalArgumentException("Income cannot be negative"); return incomes.save(new IncomeTransaction(getUser(id),request.date()==null?LocalDate.now():request.date(),request.amount())); }
    public List<IncomeTransaction> income(Long id) { getUser(id); return incomes.findByUserIdOrderByTransactionDateAsc(id); }
    @Transactional public void updateIncome(Long id, Long incomeId, UserModels.IncomeRequest request) { IncomeTransaction income=incomes.findByIdAndUserId(incomeId,id).orElseThrow(() -> new NoSuchElementException("Income not found")); income.update(request.date(),request.amount()); incomes.save(income); }
    @Transactional public void deleteIncome(Long id, Long incomeId) { incomes.delete(incomes.findByIdAndUserId(incomeId,id).orElseThrow(() -> new NoSuchElementException("Income not found"))); }
    public UserModels.PersonalizedSummary summary(Long id) { User user=getUser(id); List<IncomeTransaction> rows=income(id); List<IncomePoint> history=rows.stream().map(r->new IncomePoint(r.getTransactionDate(),r.getAmount())).toList(); List<Double> amounts=rows.stream().map(IncomeTransaction::getAmount).toList(); double average=avg(amounts); double deviation=Math.sqrt(amounts.stream().mapToDouble(v->Math.pow(v-average,2)).average().orElse(0)); double cv=average==0?0:deviation/average; double high=rows.stream().mapToDouble(IncomeTransaction::getAmount).max().orElse(0), low=rows.stream().mapToDouble(IncomeTransaction::getAmount).min().orElse(0); IncomeTransaction highRow=rows.stream().max(Comparator.comparingDouble(IncomeTransaction::getAmount)).orElse(null), lowRow=rows.stream().min(Comparator.comparingDouble(IncomeTransaction::getAmount)).orElse(null); Analytics analytics=new Analytics(history,average,high,highRow==null?null:highRow.getTransactionDate(),low,lowRow==null?null:lowRow.getTransactionDate(),cv,cv<=.3?"LOW":cv<=.6?"MODERATE":"HIGH"); FinancialProfile profile=profiles.findByUserId(id).orElse(new FinancialProfile(user,"Irregular",0,0,7)); Loan loan=loans.findByUserId(id).orElse(new Loan(user,false,0,0,0)); List<Double> recent=amounts.subList(Math.max(0,amounts.size()-7),amounts.size()); ShockStatus shock=shockService.assess(recent,amounts); double today=amounts.isEmpty()?0:amounts.get(amounts.size()-1); Recommendation recommendation=engine.recommend(today,amounts,average,cv,profile.getCurrentSavings(),profile.getDailyEssentialExpenses()*profile.getProtectionDays(),profile.getDailyEssentialExpenses(),loan.getOutstanding(),loan.getMonthlyTarget(),shock.shockMode()); SavingsBuffer buffer=new SavingsBuffer(profile.getCurrentSavings(),profile.getDailyEssentialExpenses()*profile.getProtectionDays(),profile.getDailyEssentialExpenses(),profile.getDailyEssentialExpenses()==0?0:profile.getCurrentSavings()/profile.getDailyEssentialExpenses(),profile.getDailyEssentialExpenses()==0?0:Math.min(100,profile.getCurrentSavings()/(profile.getDailyEssentialExpenses()*profile.getProtectionDays())*100)); return new UserModels.PersonalizedSummary(response(user),history,analytics,recommendation,buffer,loanResponse(loan),shock,contributions.existsByUserIdAndContributionDate(id, LocalDate.now())); }
    @Transactional public Acceptance accept(Long id) { ensureNotAcceptedToday(id); UserModels.PersonalizedSummary s=summary(id); validate(s.recommendation()); FinancialProfile p=profiles.findByUserId(id).orElseThrow(); p.update(p.getEarningFrequency(),p.getDailyEssentialExpenses(),p.getCurrentSavings()+s.recommendation().savings(),p.getProtectionDays()); profiles.save(p); Loan loan=loans.findByUserId(id).orElse(null); if(loan!=null) {loan.contribute(s.recommendation().repayment());loans.save(loan);} contributions.save(new ContributionTransaction(getUser(id),LocalDate.now(),s.recommendation().savings(),s.recommendation().repayment())); return new Acceptance(true,s.recommendation(),"Contribution recorded. Your plan is up to date."); }
    @Transactional public Acceptance customize(Long id, UserModels.CustomizeRequest request) { ensureNotAcceptedToday(id); UserModels.PersonalizedSummary s=summary(id); double availableBefore=s.recommendation().available()+s.recommendation().savings()+s.recommendation().repayment(); if(request.savings()<0||request.repayment()<0||request.savings()+request.repayment()>Math.max(0,availableBefore-s.recommendation().essentialReserve())) throw new IllegalArgumentException("Contributions must fit after essential expenses."); FinancialProfile profile=profiles.findByUserId(id).orElseThrow(); profile.update(profile.getEarningFrequency(),profile.getDailyEssentialExpenses(),profile.getCurrentSavings()+request.savings(),profile.getProtectionDays()); profiles.save(profile); Loan loan=loans.findByUserId(id).orElse(null); if(loan!=null){loan.contribute(request.repayment());loans.save(loan);} contributions.save(new ContributionTransaction(getUser(id),LocalDate.now(),request.savings(),request.repayment())); Recommendation custom=new Recommendation(s.recommendation().status(),request.savings(),request.repayment(),Math.max(0,availableBefore-request.savings()-request.repayment()),s.recommendation().essentialReserve(),s.recommendation().shockMode(),"Your custom plan keeps essentials protected."); return new Acceptance(true,custom,"Custom contribution recorded."); }
    public Acceptance skip(Long id) { return new Acceptance(true,summary(id).recommendation(),"No contribution recorded for today."); }
    private void validate(Recommendation r){ if(r.savings()<0||r.repayment()<0) throw new IllegalArgumentException("Invalid contribution"); }
    private void ensureNotAcceptedToday(Long userId) { if(contributions.existsByUserIdAndContributionDate(userId, LocalDate.now())) throw new IllegalArgumentException("Today's recommendation has already been accepted. You can accept a new plan tomorrow."); }
    private UserModels.UserResponse response(User user){ FinancialProfile p=profiles.findByUserId(user.getId()).orElse(null); Loan l=loans.findByUserId(user.getId()).orElse(null); UserModels.ProfileResponse profile=p==null?null:new UserModels.ProfileResponse(p.getEarningFrequency(),p.getDailyEssentialExpenses(),p.getCurrentSavings(),p.getProtectionDays(),p.getDailyEssentialExpenses()*p.getProtectionDays()); return new UserModels.UserResponse(user.getId(),user.getName(),user.getOccupation(),user.getIncomeType(),profile,l==null?null:loanResponse(l)); }
    private com.flowflex.api.ApiModels.Loan loanResponse(Loan l){ double progress=l.getOutstanding()+l.getContributed()==0?0:l.getContributed()/(l.getOutstanding()+l.getContributed())*100; return new com.flowflex.api.ApiModels.Loan(l.isActive()?l.getOutstanding():0,l.isActive()?l.getMonthlyTarget():0,l.getContributed(),progress,List.of(new RepaymentOption("HIGH",l.isActive()?400:0,"Contribute more on stronger days"),new RepaymentOption("NORMAL",l.isActive()?150:0,"Make a steady contribution"),new RepaymentOption("LOW",0,"Keep cash available for essentials"))); }
    private double avg(List<Double> v){return v.stream().mapToDouble(Double::doubleValue).average().orElse(0);}
}
